"""empty message

Revision ID: 4cd5fa37a8d1
Revises: 
Create Date: 2021-07-31 17:45:42.761421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd5fa37a8d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('magic', sa.String(length=256), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('used',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used')
    op.drop_table('url')
    # ### end Alembic commands ###
